version: "3.11"

services:
  api:
    container_name: api
    build: 
      dockerfile: portfolio_optimisation/api/Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_EXTERNAL_PORT:-8000}:${APP_PORT:-8000}"
    # depends_on:
    #   - redis
    volumes:
      - "./portfolio_optimisation/classes:/portfolio_optimisation/classes"
      - "./portfolio_optimisation/models:/portfolio_optimisation/models"
    networks:
      po-network:
        aliases:
          - api
  bot:
    container_name: bot
    env_file:
      - .env
    build:
      dockerfile: portfolio_optimisation/bot/Dockerfile
      context: .
    depends_on:
      - api
    volumes:
      - "./portfolio_optimisation/classes:/portfolio_optimisation/classes"
    networks:
      po-network:
        aliases:
          - bot
    environment:
      - API_HOST=http://api
      - API_PORT=8000

  # redis:
  #   container_name: redis_cache
  #   image: redis:7
  #   restart: on-failure
  #   command: --port ${REDIS_PORT:-6379}
  #   ports:
  #     - "${REDIS_EXTERNAL_PORT:-6379}:${REDIS_PORT:-6379}"

networks:
  po-network:
    driver: bridge