version: "3.9"

services:
  app:
    container_name: fastapi_app
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${APP_EXTERNAL_PORT:-8000}:${APP_PORT:-8000}"
    depends_on:
      - redis
    volumes:
      - "./app:/app/app"
  redis:
    container_name: redis_cache
    image: redis:7
    restart: on-failure
    command: --port ${REDIS_PORT:-6379}
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:${REDIS_PORT:-6379}"
